image: docker:18.09.7

services:
    - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

Hello World Test:
  stage: test
  services:
    - docker:18.09.7-dind
  script:
     - sh run_tests.sh ubuntu19.10-setup-installer-amd64.task ubuntu19.10-installer-welcome-keybd-software.yml ubuntu19.10-installer-partition-setup.yml ubuntu19.10-installer-location-useracc.yml ubuntu19.10-installer-install-basesystem.yml ubuntu19.10-installer-restart-login.yml
  artifacts:
    when: always
    paths:
      - results
pages:
  stage: deploy
  script:
  - echo 'Publish results'
  - mkdir public
  - mv results/*/* public/
  artifacts:
    paths:
    - public
