image: docker:18.09.7

services:
    - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

Debian Installer test:
  stage: test
  services:
    - docker:18.09.7-dind
  script:
     - sh run_tests.sh debian10-setup-installer-amd64.task debian10-installer-lang-location-keybd-amd64.task debian10-installer-nw-useraccnt-clock-amd64.task debian10-installer-partition-amd64.task debian10-installer-apt-sw-selection-amd64.task debian10-installer-finish-reboot-login-amd64.task
  artifacts:
    when: always
    paths:
      - results
pages:
  stage: deploy
  script:
  - echo 'Publish results'
  - mkdir public
  - mv results/*/* public/
  artifacts:
    paths:
    - public
