image: docker:18.09.7

services:
    - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

Hello World Test:
  stage: test
  services:
    - docker:18.09.7-dind
  script:
     - sh run_tests.sh ubuntu1910-setup-installer-amd64.task ubuntu1910-installer-welcome-keybd-software.task ubuntu1910-installer-partition-setup.task ubuntu1910-installer-location-useracc.task ubuntu1910-installer-install-basesystem.task ubuntu1910-installer-restart-login.task
  artifacts:
    when: always
    paths:
      - results
pages:
  stage: deploy
  script:
  - echo 'Publish results'
  - mkdir public
  - mv results/*/* public/
  artifacts:
    paths:
    - public
